# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6a09412441ac149b48d8484482b34f169d78416e14ce8a4f20492ba2dfb13a103cee561b96e4645eeeb7f08dbf15f521ccf645615105d547d7aebd5a28dd6cbd

test:
  secret_key_base: d6e3644a33275b229131337a5ff15e1dbe44bb12f311b98ca93961f6a5e3b6059a892705130a01bcac7bcb361a48b0bf459802f4ce72f4fba5bacc2535e2db5d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
